apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"15"},"creationTimestamp":"2025-06-10T03:44:57Z","generation":23,"name":"nginx-deployment","namespace":"default","resourceVersion":"126591023","uid":"1e46cf57-335a-4fad-800a-a3afe82f4a5f"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"nginx-deployment"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-06-10T11:27:55-05:00"},"creationTimestamp":null,"labels":{"app":"nginx-deployment"}},"spec":{"containers":[{"command":["hi"],"image":"nginx:latest","imagePullPolicy":"Always","name":"nginx","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2025-06-10T16:26:07Z","lastUpdateTime":"2025-06-10T20:08:05Z","message":"ReplicaSet \"nginx-deployment-7c89994d4f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-06-10T20:08:07Z","lastUpdateTime":"2025-06-10T20:08:07Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":23,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-06-10T03:44:57Z"
  generation: 24
  name: nginx-deployment
  namespace: default
  resourceVersion: "126591987"
  uid: 1e46cf57-335a-4fad-800a-a3afe82f4a5f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-10T11:27:55-05:00"
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - command:
        - hi
        image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-06-10T16:26:07Z"
    lastUpdateTime: "2025-06-10T20:08:05Z"
    message: ReplicaSet "nginx-deployment-7c89994d4f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-10T20:08:07Z"
    lastUpdateTime: "2025-06-10T20:08:07Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 24
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
